### PR TITLE
initial port to macOS

### PR DESCRIPTION
**Pull request by MP2E**
Hi! Awesome project, with these changes it works well on my M1 MacBook Pro. Hoping to stick around and fix some bugs as I hit them

### CODE REVIEW

**Comment by vampirefrog** [comment]
Can you also make a github build workflow and a status badge in the README please?

**Comment by vampirefrog** [comment]
Oh and thank you for your contribution.

**Comment by MP2E** [comment]
> Can you also make a github build workflow and a status badge in the README please?

Yes, I will work on that next.

**Comment by vampirefrog** [comment]
Here is a working macos build file, but it's very simple: https://github.com/vampirefrog/vgmio/blob/master/.github/workflows/macos.yml

**Comment by MP2E** [comment]
Thanks! Just set up the build workflow and the status badge, looks like everything is working!

**Comment by vampirefrog** [comment]
Good job, trying to figure out how to generate installers now, aparently this is possible with github actions, you can generate zip files, installers, linux packages and so on, not sure what that looks like on MacOS but on windows I can make an installer that adds v68 to the `PATH`. And you can configure github actions to do that when yoh create a tag. I'll let you know when I have one working and if you want you can make that work on MacOS too.

Thanks

**Pull request merged**
